### ISSUE TITLE
[Tech]: Add mechanism for external regulation for assets operations

### ISSUE THREAD

**Issue by vovac12** [sora-xor/sora2-network#1014]
### Problem statement

We want to support regulated assets

### Description

Currently we work with permissions pallet directly, but to make assets regulation for extensible we should move all checks to Config trait associated type

### Definition of Done

- [ ] Add trait for assets operations regulation
- [ ] Move permissions pallet logic used in assets pallet to this trait

### Requirements

- New trait should be implemented for tuples like `(A, B)`
- New trait should contain method for each assets operation like `mint`, `burn`, `transfer`, etc.

**Comment by Trezeguet1** [comment]
The task is merged, but it does not change the logic in any way, it is a task for preparing interfaces for the implementation of defi-r

We are waiting for this PR to be merged so that new extrinsics that are needed for the test can be added 
https://github.com/sora-xor/sora2-network/pull/1044

The current logic is implemented this way on the QA side:

Pallet: assets 

Methods are : mint, transfer, burn, register, update_own_balance

Purpose: the testcase should be contained in the frame of just checking that after we extract permission logic in the assets to external trait, we had all assets operation working just the same as before

The asset ID needs to be written in this format, etc:
0x020000000000000000000000000000000000000000000000000000000000000000
And for amount: 100000000000000000000

Such an extrinsik should call from a sudo account with root rights

![telegram-cloud-photo-size-2-5371086999034913087-y](https://github.com/sora-xor/sora2-network/assets/51509139/0bc779cb-880f-43f4-b86f-8f404f9043e3)

**Comment by Trezeguet1** [comment]
Testing of the task is complete
