### ISSUE TITLE
[Tech]: SB and kXOR support in Kensetsu

### ISSUE THREAD

**Issue by vovac12** [sora-xor/sora2-network#1027]
### Problem statement

We want to support SB and kXOR tokens in Kensetsu

### Description

We want to support creation of vaults with SB token as collateral and kXOR as synthetic

### Definition of Done

- [ ] Implement special vault type for SB and kXOR support

### Requirements

- [x] 1% of minted kXOR goes to buyback and burn TBCD
- [x] 1% of minted kXOR goes to buyback and burn Chameleon token

**Comment by Alexey-N-Chernyshov** [comment]
We agreed that these tokens are `Predefined Asset Ids`:
- `SB`
- `kXOR`
- `CAM`

**Comment by Nolan730** [comment]
I have some questions which "New Tokenomics" needs to solve. Some of it business, some of it technical.

1. What will the price defination of SB? I doubt its a XYKPool
2. If its not equal to XOR, what will happen to kensetsu vault when it goes up or down?
3. What will exactly happen when you sell KXOR to XOR-ETH pool?
4. Karma needs XOR-KXOR pool. Why would anyone provide lp to that pool?
5. Its told KXOR will be pegged to XOR. How it will manage to peg? Pool of XOR-KXOR + vaults buybacks?

**Comment by Tieumsan** [comment]
@Nolan730 

> 1. What will be the price definition of SB? I doubt its a XYKPool

The price of SB will be defined by the XOR-SB liquidity pool. 

> 2. If its not equal to XOR, what will happen to kensetsu vault when it goes up or down?

For now we only have one type of vault, so users will need to monitor the dollar value of their collateral to avoid having it liquidated. 

> 3. What will exactly happen when you sell KXOR to XOR-ETH pool?

XOR and XKOR liquidity is aggregated in the XOR-ETH Chameleon pool. The XOR-ETH XYK pool follows the equation `Y = ETH` and `X = (XOR + KXOR)`.
When a user sells KXOR to the XOR-ETH pool, the user gets ETH and KXOR is added to the X = (XOR + KXOR) side of the pool.

> 4. Karma needs XOR-KXOR pool. Why would anyone provide lp to that pool?

KARMA doesn’t need the XOR-KXOR pool, it needs Kensetsu XOR minted from a Kensetsu vault.

> 5. Its told KXOR will be pegged to XOR. How it will manage to peg? Pool of XOR-KXOR + vaults buybacks?

KXOR is pegged to XOR through price tools.

**Comment by Nolan730** [comment]
> XOR and XKOR liquidity is aggregated in the XOR-ETH Chameleon pool. The XOR-ETH XYK pool follows the equation Y = ETH and X = (XOR + KXOR).
When a user sells KXOR to the XOR-ETH pool, the user gets ETH and KXOR is added to the X = (XOR + KXOR) side of the pool.

I asked it at another pull request (https://github.com/sora-xor/sora2-network/pull/1041#issuecomment-2134470193) . What will happen when all xor turn to kxor inside eth pool and someone tries to buy XOR not KXOR?

> KARMA doesn’t need the XOR-KXOR pool, it needs Kensetsu XOR minted from a Kensetsu vault.

Vault needs to buy back KARMA. In order to do that, KXOR needs a pool which accepts KXOR and only xor-eth pool does that. Makoto mentioned that there will be "KXOR-XOR" pool for that. If we wont get that pool and use xor-eth pool, what will happen when there is no xor inside xor-eth pool?

> KXOR is pegged to XOR through price tools.

Which pool will provide that peg tho? I guess it will be pegged for kensetsu pool only?
