### ISSUE TITLE
Please describe the datasource for the Sora business metrics

### ISSUE THREAD

**Issue by adaagava** [sora-xor/sora2-network#103]
### Problem statement

We'd like to have the grafana board that helps us to understand that everything in the Sora network is working good right now. It will let us not to check production manually after each release. 

### Description

I have collected the list of business metrics, please find in here: https://docs.google.com/spreadsheets/d/1cMQw0XoNEbonsXvEhAZdupNtizrHKUKIYvY8Zd1-kGY/edit#gid=0

So could you please add suitable data source for each metrics. If needed, I'll make the exporter to collect them and put to the prometheus.

### Definition of Done

There is a data source for each of the metrics in the list https://docs.google.com/spreadsheets/d/1cMQw0XoNEbonsXvEhAZdupNtizrHKUKIYvY8Zd1-kGY/edit#gid=0

### Requirements

please let me know is some datasources requires special access.

**Comment by bgodlin** [comment]
@adaagava 

# Get started
Information could be extracted from the Subquery service that is running on our prod environment (more on Subquery https://soramitsu.atlassian.net/wiki/spaces/SE/pages/3448406051/Sora+Subquery). I would also suggest try running Subquery locally on the development branch (everything is already configured in the default branch https://github.com/sora-xor/sora-subquery).

The current data organisation is custom. We came up with it by ourselves and not limited to change it in the future. Most of relevant data is being stored as the `HistoryElement` entity and to understand what type of transaction was executed is possible by objects of the its entity. The data is returned in atomic form => grouping needs to be done by client application.

# Queries

## Balance transfers
```
query {
  historyElements(
    orderBy: TIMESTAMP_DESC
    filter: {
      module: { equalTo: "assets" }
      method: { equalTo: "transfer" }
    }
  ) {
    nodes {
      id
      blockHeight
      module
      method
      address
      networkFee
      execution
      timestamp
      data
    }
  }
}
```
## Swaps
```
query {
  historyElements(
    orderBy: TIMESTAMP_DESC
    filter: {
      module: { equalTo: "liquidityProxy" }
      method: { equalTo: "swap" }
    }
  ) {
    nodes {
      id
      blockHeight
      module
      method
      address
      networkFee
      execution
      timestamp
      data
    }
  }
}
```
## Pools operations
```
query {
  historyElements(
    orderBy: TIMESTAMP_DESC
    filter: {
      or: [
        { method: { equalTo: "withdrawLiquidity" } }
        { method: { equalTo: "depositLiquidity" } }
      ]
    }
  ) {
    nodes {
      id
      blockHeight
      module
      method
      address
      networkFee
      execution
      timestamp
      data
    }
  }
}
```
## Staking
Not implemented

## Rewards
Which rewards specifically are needed?

## Ethereum-bridge transactions (each direction)
```
query {
  historyElements(
    orderBy: TIMESTAMP_DESC
    filter: {
      or: [
        { module: { equalTo: "ethBridge" } }
      ]
    }
  ) {
    nodes {
      id
      blockHeight
      module
      method
      address
      networkFee
      execution
      timestamp
      data
    }
  }
}
```

## Number of the ethereum-bridge queue
You need to check with the frontend team, since the logic is not simple and requires accessing not only Subquery, but also the Ethereum node

## Number of available nodes
Could be obtained from the node logs

## Number of balance requests
Could be obtained from the node logs
