### ISSUE TITLE
[Tech Debt]: Replace uses of balances.transfer by assets.transfer

### ISSUE THREAD

**Issue by Tieumsan** [sora-xor/sora2-network#146]
### Problem statement

Both pallets are still being used when transferring assets: 
- `balances.transfer`, which is used to transfer only XOR
- `assets.transfer`, which is used to transfer any asset, XOR included

We want to have a uniform method to transfer assets to avoid side effects.
However, we first need to investigate how `balances.transfer` is used and if there is a specific reason. If not, then we'll just replace the use of `balances.transfer` by `assets.transfer`

### Definition of Done

- [x] Investigate use of `balances.transfer`
- [x] Replace uses of `balances.transfer` by `assets.transfer`
- [x] Tests
- [x] Benchmarking

**Comment by bragov4ik** [comment]
I've investigated the usage of `balances.transfer` and see two options to approach the task

1. Only prevent users from calling `balances.transfer` extrinsic
2. Do the 1st and additionally replace usages of `Balances` pallet in other modules

**Comment by bragov4ik** [comment]
We chose the 1st option, because 2nd is not cleanly achievable and is not necessary. [Details here](https://app.zenhub.com/files/356546020/62c1b513-e097-459d-bd8e-8d1fbd0c1ee5/download)

**Comment by bragov4ik** [comment]
Also, there is pallet `currencies` that acts as an adapter of `balances` for `assets`. It also has dispatchables that are called, even though rarely. We also should restrict its usage to have uniform transfer method in `assets`

**Comment by bragov4ik** [comment]
As reported by QA team - removal of calls to `currencies.update_balance` broke autotests. Since `force_mint` is apparently used for purposes other than testing (and is pretty hard to use for tests), I think it's better not to touch it and create a separate extrinsic in `assets` for test purposes.

Long-term solution is to create a separate pallet for test methods, enable it only in test networks, and put `update_balance` there. It requires a separate task and consideration, so

Short-term fix is `update_balance` root extrinsic in `assets` pallet.
