### ISSUE TITLE
[Bug][Investigate]: Infinite work of priceTools on STAGE

### ISSUE THREAD

**Issue by ra9mls** [sora-xor/sora2-network#177]
### Preconditions

XOR price >3 usd

### Steps to reproduce

1. Open https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fws.stage.sora2.soramitsu.co.jp#/chainstate
2. priceTools.priceInfos and input dai asset id (0x0200060000000000000000000000000000000000000000000000000000000000) 
3. Execute 

### Actual behavior

Price tools works infinite and not match XSTUSD price to DAI
![image](https://user-images.githubusercontent.com/17094492/201051268-ed170f65-7c29-4af2-8e76-d6800c14d42f.png)
<img width="422" alt="Screenshot 2022-11-10 at 10 06 00" src="https://user-images.githubusercontent.com/17094492/201051151-ea5fa8d8-242c-45da-89cf-445c4b5acdad.png">

XOR-DAI
31: liquidityProxy.quote: Option<LPSwapOutcomeInfo>
{
  amount: 765.6630 XOR
  fee: 3.0000 mXOR
  rewards: []
}
XOR-XSTUSD
29: liquidityProxy.quote: Option<LPSwapOutcomeInfo>
{
  amount: 17.2693 kXOR
  fee: 3.0000 mXOR
  rewards: []
}

### Expected behavior

XOR-DAI price equals XOR-XSTUSD price like on prod and dev env.

### Environment

{"label"=>"Stage"}

**Comment by CrimeaTop** [comment]
As it turns out, priceTools works correctly, decreasing the average price towards the target value at the exact pace set in the pallet config. The issue lies in XSTUSD price, which at some point became huge, so priceTools now takes a looot of time to normalize it. However, the node doesn't return storage values belonging to priceTools at that point in time, so it's problematic to discover the cause.
