### ISSUE TITLE
[Tech]: Add amountWithoutImpact

### ISSUE THREAD

**Issue by stefashkaa** [sora-xor/sora2-network#241]
### As a

Developer

### I want to

have amountWithoutImpact returned from liquidityProxy.quote rpc

### So that

I see the price impact from the liquidity proxy quote

### Preconditions

`liquidityProxy.quote` is called with `skip_info` flag set to `false`

### Flow

`amount_without_impact` is calculated

### Postconditions

`amount_without_impact` is returned with as a part of result

**Comment by Tieumsan** [comment]
@vovac12 how hard / resource consuming is it to return the swap route with the quote ?
What about the price impact ?

**Comment by Tieumsan** [comment]
@bgodlin we need SA/requirements review on this

**Comment by bragov4ik** [comment]
According to Nikita Polyakov there is no up-to-date document with description of formulae or logic for quoting. Therefore it seems that we should refer or use existing code for calculations.

Formulae for calculation of `amountWithoutImpact` are already present in backend in corresponding functions `quote_without_impact`. They are up-to-date and relevant, as told by Nikita.
Also application of these formulae is not straightforward, since `quote` logic became quite complex after removal of `amountWithoutImpact`. Apparently, the [relevant logic from frontend](https://github.com/sora-xor/sora2-substrate-js-library/blob/d6421615199181aa9cb2c249bcd5e7db35e1d7b5/packages/liquidity-proxy/src/liquidityProxy.ts#L510) should be applied here. I'll try to clarify its relevance and some unclear details.

**Comment by bragov4ik** [comment]
btw it's worth mentioning that this feature was present before and removed in [this PR](https://github.com/soramitsu/sora2-substrate/pull/761). Simple `git revert` won't work because logic/mechanism of `quote` was change pretty drastically since then.
