### ISSUE TITLE
[Tech]: Delete order book optimization

### ISSUE THREAD

**Issue by wer1st** [sora-xor/sora2-network#711]
### Problem statement

By benchmarks we found that order-book deleting takes too much time in worst case. Necessary to optimize that process.

### Description

It is needed to implement new approach for order-book deleting.
Now we can delete only empty order-book in states: `OnlyCancel` or `Stop`.

Dev changes:
- Don't cancel any orders
- Check that order-book is empty
- Check that order-book has states `OnlyCancel` or `Stop`
- Delete order-book if all conditions are met.

Delete order-book from the user perspective:

1. Announce the delisting of pair from order book liquidity source.
2. Change order-book status to `OnlyCancel` or `Stop`.
3. Wait untill users cancel their limit orders or they expire. Order-book must be empty.
4. Call `order-book::delete_orderbook()` extrinsic.

### Definition of Done

- [x] Order-book is not deleted if it has any statuses other than`OnlyCancel` or `Stop`.
- [x] Order-book is not deleted if it has at least one limit-order.
- [x] Deleting of order-book doesn't cancell any orders.
- [x] Order-book is deleted by `delete_orderbook` extinsic if all conditions are met.
- [x] Update unit tests.
- [x] Update benchmarks.
- [ ] Update autotests if it necessary.

**Comment by bragov4ik** [comment]
A suggestion: instead of disallowing removal of order books that contain any orders, we can allow cancellation of up to $N$ orders where $N$ is small enough so that the removal is as short as needed.

**Comment by bragov4ik** [comment]
> we can allow cancellation of up to $N$ orders
After a discussion we concluded that we won't implement it this way because
* It can be ambiguous from user perspective (sounds like an arbitrary and weird restriction)
* There is no easy indicator of order book having $N$ orders, in contrast to being empty
* The implementation would be additional code that can introduce additional bugs, weaknesses, etc.
* There is no clear motivation to allow quick(-er) removal of the order book

**Comment by ra9mls** [comment]
https://app.qase.io/case/PSS-159
