### ISSUE TITLE
Accrue calls spamming protection

### ISSUE THREAD

**Issue by Alexey-N-Chernyshov** [sora-xor/sora2-network#878]
## Problem statement
The beneficiary of Kensetsu wants to call accrue on every CDP as often as possible to get income from stability fee. In order to get a fee waiver for the protocol owner, accrue call done as unsigned tx. There are lots of CDPs in the system, and spamming with accrue calls could overload the system. There are protection parameter in the system named livetime of tx that prevents of double sending during some time. We need additional level of protection in accrue tx validation.
## Solution
1) It might be a timestamp of last accrue call in CDP - it is bad since requires additional storage.
2) We can sink only accrue calls that pay only fee amount larger than some threshold or make CDP unsafe. The better solution.

**Comment by ra9mls** [comment]
Accure: about 5000 cdps cause an expected high load on env-t (>60% cpu) because it try to accure to every cdp every 10 sec and don't fit in block. Will check with accure every 10 minutes.
<img width="1062" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOEk2QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--dccc4620d9f07270a25db8467a6fbe5c7fbd4da0/Screenshot%202024-04-05%20at%2015.15.52.png" alt="Screenshot 2024-04-05 at 15.15.52.png" />
